name: Kabir
favicon: null
layout_spectrum: 1
typography_spectrum: 0.45789775461889803
title: Kabir the Great
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.026851285016164184
  lightness: 0.5788283101283014
  saturation: 0.9115060174372047
  rhythmicContrast: 0.9830340140033513
purpose: []
